### ISSUE TITLE
Tup doesn't support 64-bit compilers on Windows

### ISSUE THREAD

**Issue by pfmoore** [gittup/tup#168]
It looks like the available tup binaries for Windows don't support 64-bit compilers like mingw64 or Visual Studio.

```
tup error: failed to inject dll: No such file or directory
```

Basically, this makes tup useless on 64-bit Windows :-( Any chance of a 64-bit build (that will support both 64-bit and 32-bit tools, obviously...)?

**Comment by gittup** [comment]
Robert's 64-bit Windows patches have been merged, so I'm closing this. If there are still issues, please let me know.

**Comment by cpkio** [comment]
The problem still persists on Windows 10 x64.
_Tupfile_ is `: tick.go |> go build %f |> %B.exe`
`tup.exe`, `tup32detect.exe`, `tup-dllinject.dll` & `tup-dllinject32.dll` are all in path.
And still
```
$ tup
[ tup ] [0.002s] Scanning filesystem...
[ tup ] [0.005s] Reading in new environment variables...
[ tup ] [0.006s] Parsing Tupfiles...
 0) [0.001s] .
 [ ] 100%
[ tup ] [0.010s] No files to delete.
[ tup ] [0.010s] Generating .gitignore files...
[ tup ] [0.012s] Executing Commands...
 [ ]   0%tup error: failed to inject dll: No such file or directory
 *** Command ID=26 failed: go build tick.go
 [ ]   0%
 *** tup: 1 job failed.
```

**Comment by gittup** [comment]
> The problem still persists on Windows 10 x64.
> _Tupfile_ is `: tick.go |> go build %f |> %B.exe`
> `tup.exe`, `tup32detect.exe`, `tup-dllinject.dll` & `tup-dllinject32.dll` are all in path.

Is `go.exe` also in your path? I got the same error when go wasn't in the path, but once I added it, I was able to compile a hello-world.go

**Comment by cpkio** [comment]
Sure it is. I execute `go build tick.go` just fine and it builds to `tick.exe`.

I reported this error while being on Win10x64 machine, and now I'm at home on Win7x64 machine, and still it doesn't work as expected. Something's going on with those DLLs, I wonder.
