### ISSUE TITLE
if job_numbers is expected to be >= 10, pad accordingly

### ISSUE THREAD

**Issue by sudoman** [gittup/tup#191]
when tup is compiling source code, it already knows how many files it will compile. however, when printing numbers for each job, there ought to be an extra space after the single-digit numbers, for the sake of vertical alignment. (if the total number of jobs is >= 10 and < 100.)

````
   9% 8) [0.082s] src/lua: CC lmem.c
  10% 9) [0.048s] src/lua: CC lopcodes.c
  11% 10) [0.250s] src/lua: CC lobject.c
  12% 11) [0.440s] src/lua: CC llex.c
````
it would make the output look much nicer.

of course, when listing directories, the total number of directories may not be possible to predict without exploring the directory structure in advance. in that case, it may make sense to add the extra padding after the single digit by default. if there are >= 100 directories to list, then the vertical alignment will break at 100, but remain good until it reaches 1000.

the padding of the compiler numbers ought to be equal to (or greater than) the padding for the directory structure.

**Comment by Qix-** [comment]
Side note: Thank you @gittup for hitting all of these headstrong :) Glad to see a breath of life back into this.
