### ISSUE TITLE
Document how to use %<group> in commands

### ISSUE THREAD

**Issue by gittup** [gittup/tup#193]
<groups> are currently documented in the man page, but how to use %<group> in a command string to expand the group dynamically is not. This should be documented.

**Comment by erikbrinkman** [comment]
There also appears to be a little weirdness in using the %<group> tag in commands when there are two groups with the same name in different directories. It does generally what I would want but it seems a little strange that you can't address groups by directory.

```
: a/<group> |> echo %<group> |>
```

echoes all of the files in `a/<group>`

```
: a/<group> b/<group> |> echo %<group> |>
```

echoes all of the files in both groups. As far as I know the only way to echo the files individually would be to use different group names. This is a strange edge case, and I don't really think it needs to be "fixed". I'm not sure what a more desired behavior would be, but it felt appropriate to document.
