### ISSUE TITLE
Using same {bin} in multiple tupfiles doesn't work.

### ISSUE THREAD

**Issue by p2rkw** [gittup/tup#221]
Let's say I have following directory structure:
.
├── main.cpp
├── main.o
├── module1
│   ├── module1.cpp
│   ├── module1.o
│   └── Tupfile
├── module2
│   ├── module2.cpp
│   ├── module2.o
│   └── Tupfile
└── Tupfile

and my tupfiles:

$ cat module1/Tupfile 
: module1.cpp |> g++ -c -o %o %f |> module1.o {objs}

$ cat module2/Tupfile 
: module2.cpp |> g++ -c -o %o %f |> module2.o {objs}

$ cat Tupfile
: main.cpp |> g++ -c -o %o %f |> main.o {objs}
: {objs} |> g++ -o %o %f |> a.out

When I run tup, I got following output:
(...)
 1) [0.095s] module2: g++ -c -o module2.o module2.cpp                                        
 2) [0.095s] g++ -c -o main.o main.cpp                                                       
 3) [0.095s] module1: g++ -c -o module1.o module1.cpp                                        
* 4) g++ -o a.out main.o  
(...)

As you can see bin {objs} only contain 'main.o'. User manual confirms that:
`You can't remove things from a bin, and the bin disappears after the current Tupfile is parsed.`

Why 'bins' are private for single Tupfile? How can I make them global?

I saw tup's Tupfile and I think it only workaround this problem, it's not elegant.

I don't want to have one global Tupfile with all source directories listed inside.

**Comment by KamilSzczygiel** [comment]
You cannot make `{bin}` global, but you can use another feature for that - groups. Groups have a path, so if you have:

    TOP = $(TUP_CWD)

in your top-level `Tuprules.tup`, then you can use groups in any `Tupfile` as a global variable like that:

    : foreach *.cpp |> $(CXX) $(CXXFLAGS) $(CXXFLAGS_%f) -c %f -o %o |> $(OUTPUT)%B.o $(TOP)/<objects>

In the top-level `Tupfile` you can omit the path and use the group like this:

    : <objects> |> $(LD) $(LDFLAGS) %<objects> -o %o |> $(PROJECT).elf

Note that groups are not expanded by most of `%-flags` - to expand a group in command you need to use special `%<...>` flag, with "..." being the name of group passed as rule input. If i remember correctly, this feature is not documented, but there are some nice examples in the test cases.

**Comment by p2rkw** [comment]
I modified my main tupfile:
> : main.cpp |> g++ -c -o %o %f |> main.o \<objs\>
>  \<objs\> |> g++ \<objs\> -o %o |> a.out

This still didn't resolve my problem, because now I have following output:
```
 1) [0.022s] module1: g++ -c -o module1.o module1.cpp                                        
 2) [0.029s] module2: g++ -c -o module2.o module2.cpp                                        
 3) [0.029s] g++ -c -o main.o main.cpp                                                       
* 4) g++ <objs> -o a.out                                                                     
/bin/sh: 1: cannot open objs: No such file
```

**Comment by p2rkw** [comment]
Hi Kamil,
I changed my main tupfile to:
```
: main.cpp |> g++ -c -o %o %f |> main.o <objs>
: <objs> |> g++ %<objs> -o %o |> a.out
```
and it works. It's so useful that it should be documented :)
Thanks for your help.

**Comment by KamilSzczygiel** [comment]
There's even an issue for that #193 (;

**Comment by p2rkw** [comment]
Another thing is that this solution doesn't play nice with macros. When `<group>` is used as input dependency %f isn't substituted with group contents, but with group name.

**Comment by p2rkw** [comment]
As [comment in source code](https://github.com/gittup/tup/blob/master/src/tup/parser.c#L3795) says, rule gets expanded more than once, so I end with this:
Tuprules.tup:
```
!cxx = |> g++ -c %f -o %o $(cxxFlags) $(CXXFLAGS) |>
!ld = |> g++ %%%f -o %o $(ldFlags) $(LDFLAGS) |>
```
Tupfile:
```
include_rules
: <objs> |> !ld |> a.out
```

**Comment by KamilSzczygiel** [comment]
Whether or not groups "play nice with macros" depends on what you want to accomplish. In my projects I only pass the group to linking, so I see no problem of using `%<objects>` in the rule. I didn't even knew about this multiple expansion rule (;
