### ISSUE TITLE
open/open_at syscalls with the O_DIRECTORY flag on linux shouldn't add dependencies

### ISSUE THREAD

**Issue by pjump** [gittup/tup#222]
I ran into this issue while trying to use `bundler` with `tup`.
Bundler searches the current directory for `*.gemspec` files recursively using `Dir['{,*,*/*}.gemspec']` in ruby, which triggers `openat` `O_DIRECTORY`-flagged syscalls on every file in the directory recursively.
Tup registers these as new dependencies  (which makes everything dependent on everything), and I don't think it should, since the calls autofail on all file paths that aren't directories.

**Comment by KamilSzczygiel** [comment]
You should really add some formatting to this issue (; Try backticks for code/shell snippets - this way they will be shown correctly.

**Comment by pjump** [comment]
@KamilSzczygiel Done

**Comment by pjump** [comment]
Basically, filtering out `O_DIRECTORY`-flagged `open` calls, if possible,  would be good for build scripts that find their dependencies dynamically by scanning the repo tree for certain files. `fstat` call add dependencies too, so currently, as far as I understand, there's no way to have dynamic dependencies (e.g., dependencies based on a file name format)  in the whole repo tree without adding everything as a dependency.
