### ISSUE TITLE
Problem with Windows Tup

### ISSUE THREAD

**Issue by mparanjpe** [gittup/tup#228]
I'm having licensing problems running Tup on Windows with IAR's Embedded Workbench.  Specifically, I'm running the iccarm program.

I have two files in the current directory: `main.c` and `Tupfile`.  These files are listed below:

**main.c**

    int
    main( int argc, char **argv )
    {
        printf( "Wha tup\n" );

        return 0;
    }

**Tupfile**

    : main.c |> iccarm %f -o %o |> %B.o

If I run `tup upd` in this directory, I get an error:

    $ tup upd
    [ tup ] [0.020s] Scanning filesystem...
    [ tup ] [0.040s] Reading in new environment variables...
    [ tup ] [0.060s] Parsing Tupfiles...
     1) [0.010s] .
     [ ] 100%
    [ tup ] [0.070s] No files to delete.
    [ tup ] [0.080s] Generating .gitignore files...
    [ tup ] [0.100s] Executing Commands...
    * 1) iccarm main.c -o main.o
    
       IAR ANSI C/C++ Compiler V6.70.2.6274/W32 for ARM
       Copyright 1999-2013 IAR Systems AB.
    Fatal error[LMS001]: License check failed. Use the IAR License Manager to
              resolve the problem.
    Error in LcGetSelectedLicensesPath
    [LicenseCheck:2.13.4.627, RMS:8.5.0.0021, Feature:ARM.EW.COMPILER,
              Version:1.02]
    Fatal error detected, aborting.
     *** tup errors ***
     *** Command ID=20 failed with return value 2
    tup error: Expected to write to file 'main.o' from cmd 20 but didn't
     *** Additionally, command 20 failed to process input dependencies. These should probably be fixed before addressing the command failure.
     [ ] 100%
     *** tup: 1 job failed.

However, if I run the command directly, there is no error:

    $ iccarm main.c -o main.o
    
       IAR ANSI C/C++ Compiler V6.70.2.6274/W32 for ARM
       Copyright 1999-2013 IAR Systems AB.
    
     36 bytes of CODE memory
    
    Errors: none
    Warnings: none

It almost seems like there are problems with the PATH since there are spaces.  The PATH entries relevant to IAR are:

    c:/Program Files (x86)/IAR Systems/Embedded Workbench 6.5/arm/bin

and

    c:/Program Files (x86)/IAR Systems/Embedded Workbench 6.5/common/bin

Any ideas what might be going on?

**Comment by gittup** [comment]
I don't have any experience with IAR's tools. Perhaps their licensing check requires additional environment variables to work? If so, you might just need to use 'export FOO' in the Tupfile to make sure they are in the environment.

**Comment by ofaurax** [comment]
I solved this problem by setting the environement variable SYSTEMDRIVE to C:

    export SYSTEMDRIVE=C:
