### ISSUE TITLE
tup ignores files beginning with the `.` character

### ISSUE THREAD

**Issue by gaye** [gittup/tup#238]
I would like for tup to not ignore them :)

**Comment by michaelmior** [comment]
It would be nice if this were a configurable option.

**Comment by gittup** [comment]
Hidden files are allowed as of e5b0b379a1ce1aa9ad2ff9ae4a51d3b9dc5262c3, though ".tup", ".git", and ".hg" are still ignored. We may need to add some support for specifying other files to be ignored in a rule something, though.

**Comment by gittup** [comment]
Closing this for now. If there are ideas for further enhancements, please file a new issue.

**Comment by jhasse** [comment]
If I'm not mistaken, `tup monitor --forground --autoupdate` still seems to ignore them (in my case it's a configuration file for `clang-tidy` which name is `.clang-tidy`). Is this correct?

**Comment by gittup** [comment]
Ahh, I had a patch lying around to fix that but hadn't merged it yet. Please give the latest with revision e3d4a32ac5bf9af69f7ade6f544ba7f0dd8bbfd1 a shot.
