### ISSUE TITLE
OSX Brew: Error - No available formula for tup

### ISSUE THREAD

**Issue by ccostes** [gittup/tup#241]
Trying to install on OSX 10.10.5 and have already installed osxfuse, but when I try to install tup using 
`brew install tup` is says `Error: No available formula for tup`.

Any idea what the problem could be? I'm new to Mac, so it's entirely possible I'm doing something dumb.

**Comment by tegimeki** [comment]
Perhaps try `brew update`?

**Comment by tegimeki** [comment]
Actually, I just ran `brew update` and it showed `tup` as one of the deleted formulae.  Maybe it moved and needs to be added via `brew tap`?  It shows up under "Inactive" on http://brewformulas.org so I'm not sure what happened.

**Comment by tegimeki** [comment]
Okay here is a (possible) real lead:  tup looks to have moved to https://github.com/Homebrew/homebrew-fuse, so run `brew tap homebrew/fuse` then you should be able to install it.

**Comment by ccostes** [comment]
Ah, perfect. After tapping homebrew/fuse I am able to use `brew install homebrew/fuse/tup` successfully!
