### ISSUE TITLE
tup without fuse

### ISSUE THREAD

**Issue by michaelmior** [gittup/tup#244]
Is there any way it would possible to run tup without fuse for one-time builds? In my case, I'd like to use tup as a build system for a CI service which doesn't support fuse. I don't care about dependency tracking because I'm only ever going to run the build once. I'm guessing it's possible to run tup without fuse in this scenario, but wondering if you have a sense of how challenging that would be to implement.

**Comment by michaelmior** [comment]
I discovered this is already solvable with `tup generate` as this command doesn't require fuse and neither does the generated script.

**Comment by p2rkw** [comment]
Is there any manual for 'tup generate'?

**Comment by michaelmior** [comment]
It doesn't seem to be documented, but I just use `tup generate build-once.sh` from a clean checkout (with no tup database) and I get a plain shell script that contains the necessary build commands (with no dependency checks).

It would be nice to know if this is something that is planned to be maintained though, and hopefully it is.

**Comment by gittup** [comment]
I started to document it in commit
6cf260ad2b0b07ea54b850b0b577e83a802acc8d. Please let me know if any
additional information would be helpful.

I don't see any reason we can't continue to maintain 'tup generate' going
forward, since it seems pretty well scoped.

-Mike

**Comment by michaelmior** [comment]
@gittup Awesome! The documentation covers anything that immediately comes to mind for me.
