### ISSUE TITLE
tup generate produces -x script

### ISSUE THREAD

**Issue by naudhr** [gittup/tup#251]
Is it absolutely necessary to unconditionally write down a verbose script?
```c
fprintf(generate_f, "#! /bin/sh -ex\n");
```
Even on a medium-size project the stdout gets littered a lot.

While introducing a separate option (like `tup generate --shebang_opt eBxUC b.sh` with the preserved default behaviour) might be overkill (one seldom specifies anything except `-e` and `-x`), a way to configure `-x` presence would be quite nice.

**Comment by p2rkw** [comment]
Never used that, but another command line switch just for that looks like overcomplicated solution.

Why can't you simply do 'bash b.sh'?

**Comment by gittup** [comment]
I'd be fine with making the default not use -x, and adding an option like
--verbose-script or some such that adds it back in.

**Comment by gittup** [comment]
Fixed by a17bf0f823aff5dd24d87c84ca506038baee365f
