### ISSUE TITLE
Using ^c with HEAD in OS X

### ISSUE THREAD

**Issue by xguerin** [gittup/tup#253]
What is the new rationale to use chrooted commands with OS X ? I am getting the following error:

``
This process requires namespacing, but this kernel does not support namespacing and tup is not privileged. You'll need to upgrade your kernel, or compile tup with CONFIG_TUP_SUDO_SUID=y in order to support the ^c flag.
``

And my TUP binary is privileged:

``
-rwsr-xr-x 1 root 1004K Dec 18 10:14 tup
``

Edit: this looks related to the new SIP feature in El Capitan. Any clues ?

**Comment by gittup** [comment]
It looks like I just broke it while adding Linux namespacing, since I don't have test coverage for OSX with an suid binary. I should have a fix out soon.

**Comment by gittup** [comment]
Can you try the latest master?

**Comment by Qix-** [comment]
Correct me if I'm wrong, but doesn't the running user need to be root? It doesn't really matter what user:group permissions are on the file. Privileging an application is more than just setting its user:group to `root`, right?

**Comment by gittup** [comment]
The 's' flag in the permissions here is the suid bit, which if it's owned by root gives the program effective root permissions. Tup is then able to do chroot() (which a normal user can't do), and then drops the root privileges before invoking subprocesses (gcc or whatever).

**Comment by Qix-** [comment]
Oh I didn't even see `s`. Never mind.

**Comment by xguerin** [comment]
It's working great. Thanks.
