### ISSUE TITLE
Console output is garbled on Windows with most recent tup

### ISSUE THREAD

**Issue by FreddieChopin** [gittup/tup#255]
I've just tried most recent version of tup on Windows 7 64-bit (in Virtual Box) and the output in console is a complete mess.

![screenshot_20151226_005345](https://cloud.githubusercontent.com/assets/1139038/12004640/5fe67424-ab6b-11e5-990f-58d141dcb65f.png)

The previous version I used in this system - tup-v0.7.3-18-g8e63ea4 - did not have this problem.

**Comment by FreddieChopin** [comment]
The commit that breaks it is https://github.com/gittup/tup/commit/7f0a6916ad6b4c37cb0394be3089ff121e23b5cb . This compilation has the problem - tup-v0.7.3-105-g7f0a691, this one doesn't - tup-v0.7.3-104-g65fdf0f

**Comment by gittup** [comment]
I changed this again slightly in 31a787fa3e696951bcaf123d95a3b2ba16b653f0 - let me know if you have any trouble with it.

**Comment by FreddieChopin** [comment]
well, the output looks correct, so no trouble to report at this moment (; Thanks for the fix!
