### ISSUE TITLE
Regression: variable with %d referenced from macro in Tuprules.tup

### ISSUE THREAD

**Issue by dyu** [gittup/tup#257]
This worked in 0.7.x but no longer works with master branch:
NAME = %d
!cxx_shared_o = |> $(CXX) $(SHARED_FLAGS) -o %o %f $(LINK_FLAGS) |> lib$(NAME).so

It doesn't evaluate the %d so the output file would be lib%d.so.
0.7.x would eval the %d correctly.

**Comment by gittup** [comment]
Thanks for the report! I should have this fixed shortly. It's a little weird, since outputs need to have %-flags expanded both before and after $-variable expansion to also account for constructions like $(CFLAGS_%f) when you have variables like CFLAGS_foo.c += -DFOO or something.
