### ISSUE TITLE
tup.getcwd() does not behave as expected with Tupdefault.lua

### ISSUE THREAD

**Issue by TheGoctor** [gittup/tup#258]
From the Lua parser documentation:
> In the following documentation, PROCESSING refers to the directory Tup is currently processing, and RUNNING refers to the directory of the build definition file Tup is currently running. When Tup enters Tupfile.lua, PROCESSING and RUNNING are the same. When running Tuprules.lua, Tupdefault.lua, or an included file, PROCESSING AND RUNNING may be different.

I expect this to mean RUNNING would be the directory containing Tupdefault.lua and PROCESSING to be the directory currently being processed by tup. Instead, `tup.getcwd()` always returns '.' as the current directory when called in Tupdefault.lua.

Here's an example:
```bash
$ mkdir dir
$ mkdir dir/subdir
$ echo "tup.rule('echo ' .. tup.getcwd())">Tupdefault.lua
$ tup init && tup
.tup repository initialized.
[ tup ] [0.010s] Scanning filesystem...
[ tup ] [0.027s] Reading in new environment variables...
[ tup ] [0.048s] Parsing Tupfiles...
 1) [0.002s] .
 2) [0.002s] dir
 3) [0.002s] dir\subdir
 [   ] 100%
[ tup ] [0.056s] No files to delete.
[ tup ] [0.065s] Executing Commands...
 1) [0.045s] dir: echo .
.
 2) [0.047s] dir\subdir: echo .
.
 3) [0.054s] echo .
.
 [   ] 100%
[ tup ] [0.131s] Updated.
```

**Comment by gittup** [comment]
I think this is intended - Tupdefault.lua behaves as if you copied this file into each directory as Tupfile.lua. So if you had tup.rule('echo ' .. tup.getcwd()) in dir/subdir/Tupfile.lua, you would expect to see "echo ." as the rule, right?

In general, you probably want to use tup.getcwd() in Tuprules.tup files rather than Tupfile.lua / Tupdefault.lua

**Comment by TheGoctor** [comment]
That's what I would have thought had it not been for the last statement in the documentation quote:
> When running Tuprules.lua, Tupdefault.lua, or an included file, PROCESSING AND RUNNING may be different.

This seems to explicitly call out Tupdefault as being treated differently than Tupfile.

**Comment by gittup** [comment]
Ahh, thanks for pointing that out. I'll update the doc and mark it to close this issue. If you think there is still another issue that needs to be addressed here feel free to reopen or file another.

**Comment by TheGoctor** [comment]
Does this mean the only way to include files in Tupdefault is to use a Tuprules file as an anchor? 
Consider this case:
```bash
$ echo "tup.rule('echo works')">include.lua
$ echo "tup.include(tup.getcwd() .. 'include.lua')">Tupdefault.lua
$ tup
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.021s] Reading in new environment variables...
[ tup ] [0.022s] Parsing Tupfiles...
 1) [0.002s] .
 [ ] 100%
[ tup ] [0.025s] No files to delete.
[ tup ] [0.048s] Executing Commands...
 1) [0.084s] echo works
works
 [ ] 100%
[ tup ] [0.156s] Updated.
```

This works fine until you add a new subdirectory for Tupdefault to parse:
```bash
$ mkdir subdir
$ tup
[ tup ] [0.001s] Scanning filesystem...
[ tup ] [0.019s] Reading in new environment variables...
[ tup ] [0.020s] Parsing Tupfiles...
* 1) [0.002s] subdir
tup error: Unable to find tup entry for file './include.lua'
tup error: Failed to parse included file './include.lua'
tup error [string "../Tupdefault.lua"]:1: Failed to include file './include.lua'.
stack traceback:
        [C]: in function 'include'
        [string "../Tupdefault.lua"]:1: in main chunk
 [ ] 100%
 *** tup: 1 job failed.
```

Is the correct solution to create a Tuprules.lua file for Tupdefault to use as an anchor?
```lua
-- ./Tuprules.lua
DIR = tup.getcwd()  -- Replace 'tup.getcwd()' in Tupdefault.lua with 'DIR'.
```
 I, for one, think it makes more sense to keep RUNNING at the original file location and PROCESSING as the subdirectory to make specifying paths less error-prone. Otherwise, I see no reason to ever use tup.getcwd() in Tupdefault.lua.

**Comment by gittup** [comment]
I think a separate Tuprules.lua to set an anchor is probably the way to go as currently implemented. On the one hand, I think you're right that it makes sense for a Tupdefault.lua to be able to include files relative to itself. On the other hand, I think it is also useful for a Tupdefault.lua to be able to include a file relative to the current directory being parsed. For example, you could create a Tupdefault.lua at the top of a Makefile-based project, and do tup.include('Makefile'), which would include the Makefile in each directory. If it's a data-driven Makefile, those variables could be read directly by tup in some cases.

Maybe there's a better syntax to distinguish between those two cases, but I think they are both useful.
