### ISSUE TITLE
[benchmark] tup is the slowest among make and ninja

### ISSUE THREAD

**Issue by pickfire** [gittup/tup#268]
Hi, I did a [benchmark for tup](https://p.iotek.org/ncf) for 1000 c files. It seems like tup is the slowest, when I use `tup --quiet`, tup is still the slowest although there is a 15s improvement.

I had benchmark it for 1 and 100 c files too, tup is still the slowest.

Here is the source for a single c file:
```bash
curl -s https://p.iotek.org/ad0 | tar xj
```

Edit:
-----
Here is the source for a c file generator:
```bash
curl -s https://p.iotek.org/s9b | tar -xj
```

**Comment by sboukortt** [comment]
Was the tup monitor running?

**Comment by pickfire** [comment]
@sboukortt What do you mean tup monitor?

**Comment by sboukortt** [comment]
The monitor is one of the main reasons why tup is so fast.

From [the manual](http://gittup.org/tup/manual.html):

> **monitor**

> \*LINUX ONLY\* Starts the inotify-based file monitor. The monitor must scan the filesystem once and initialize watches on each directory. Then when you make changes to the files, the monitor will see them and write them directly into the database. With the monitor running, 'tup' does not need to do the initial scan, and can start constructing the build graph immediately. The "Scanning filesystem..." time from 'tup' is approximately equal to the time you would save by running the monitor. When the monitor is running, a 'tup' with no file changes should only take a few milliseconds (on my machines I get about 2 or 3ms when everything is in the disk cache). If you restart your computer, you will need to restart the monitor.

**Comment by pickfire** [comment]
@sboukortt I tried to use `tup monitor`, it is even slower than without using it, I didn't even know a build system need a file monitor. Here is the result:

http://dl.pickfire.wha.la/dummy/bench.log

**Comment by sboukortt** [comment]
The intent behind the monitor is to leave it running in the background, so for a fair benchmark, probably only the subsequent invocation of `tup` should be timed (at least for the “Edit a single file” case).

**Comment by pickfire** [comment]
@sboukortt, well actually I am not very sure about that, you sure can test it yourself http://git.pickfire.wha.la/dummy

**Comment by pickfire** [comment]
Seems like tup is faster than make when I retry it on another computer this time (using 1000 files).
```
> time tup
10.53user 3.85system 0:10.09elapsed 142%CPU (0avgtext+0avgdata 29684maxresident)k
56592inputs+0outputs (0major+2809906minor)pagefaults 0swaps
> time make
10.34user 3.19system 0:18.36elapsed 73%CPU (0avgtext+0avgdata 30176maxresident)k
0inputs+0outputs (0major+2702903minor)pagefaults 0swaps
```
But those outputs make tup looks a lot slower. Maybe it's because tup's updated?
