### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by luigino** [gittup/tup#296]
This is what rpmlint tells me:
```
tup.x86_64: W: missing-call-to-setgroups-before-setuid /usr/bin/tup
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
```

Version 0.7.5

**Comment by gittup** [comment]
Thanks for finding this! There should be a fix out later today.

Are you building the rpm yourself or did you download it from somewhere? I wasn't able to find a v0.7.5 rpm online, but I don't normally use an rpm distribution. Should we be including the spec file in tup itself?

**Comment by luigino** [comment]
Thanks for the prompt reply.

I packaged it for openSUSE (it's in the devel:tools:building repository, but I think there are a couple of tweaks missing in the specfile still).

I also patched platforms.c for building on aarch64 and s390x, but I'm not sure if that counts as "support".

As feature request, would it be possible to have dynamic lua support? Or is tup too tightly knit with the version it ships?

**Comment by gittup** [comment]
What do you mean by "dynamic lua support"? The only thing I found searching has something to do with C#, so I don't think it's right :)

We include Lua 5.3.3 in the build, along with a few customizations to support a more natural syntax for build rules (like +=). The customizations probably mean it is tightly knit, but I'm not sure if that prohibits what you're trying to do.

**Comment by luigino** [comment]
Sorry, I was merely referring to the possibility of using the system library when available.

But if it's patched, I guess the point is moot.
