### ISSUE TITLE
[Security] missing-call-to-chdir-with-chroot

### ISSUE THREAD

**Issue by luigino** [gittup/tup#297]
Another complaint from rpmlint:
```
tup.ppc64le: W: missing-call-to-chdir-with-chroot /usr/bin/tup
This executable appears to call chroot without using chdir to change the
current directory. This is likely an error and permits an attacker to break
out of the chroot by using fchdir. While that's not always a security issue,
this has to be checked.
```
but in this case only on non-x86 build architectures.

Could be a false positive.

**Comment by gittup** [comment]
I think this is a false positive? Here's the only place we do a chroot(): https://github.com/gittup/tup/blob/master/src/tup/server/master_fork.c#L436

As you can see, there's a chdir("/") directly after it. Maybe it has something to do with the error checking and how the branching instructions are generated on your architecture?

**Comment by luigino** [comment]
This was a false positive caused by terrible coding on rpmlint's part.
Sorry for having wasted your time.

Regards
