### ISSUE TITLE
Circular dependency error when using !tup_preserve macro

### ISSUE THREAD

**Issue by siriobalmelli** [gittup/tup#302]
Hi there, me again :)

This is the real error I've been running into, but I didn't want to report until I had tested with the latest code version (but latest versions had that `pel` thing, thank you for fixing that one so quickly).

Same dummy build tree that replicates the issue [here](https://github.com/siriobalmelli/tup_build_C)

Specific details on that error message are [here](https://github.com/siriobalmelli/tup_build_C/blob/master/TUP_BUGS.md).

FWIW, this may be a Layer 8 bug but I really can't figure out how I'm introducing the circular dependency (the !tup_preserve is ONLY in the subdirectory Tupfile, which is not included elsewhere so it really should only be being run once).

all the best,

Sirio

**Comment by TonyTheLion** [comment]
Hey I seem to have a similar problem.

**Comment by 0joshuaolson1** [comment]
@siriobalmelli both links are 404.

**Comment by siriobalmelli** [comment]
Thank you sir.

Unfortunately I gave up on Tup - spent quite a bit of time fighting to get things working; and could never get seamless composability (easily include an external standalone project as a subproject).

After more tinkering with other build options I’ve settled on http://mesonbuild.com/ <http://mesonbuild.com/> as a big (not incremental) improvement over other build systems.

Here are some projects I have building with Meson:
https://github.com/siriobalmelli/nonlibc <https://github.com/siriobalmelli/nonlibc>
https://github.com/siriobalmelli/memorywell <https://github.com/siriobalmelli/memorywell>

Thanks again for following up.

best,

Sirio
