### ISSUE TITLE
Add %B substitution in order only inputs

### ISSUE THREAD

**Issue by erikbrinkman** [gittup/tup#306]
This may be by design, but %B does not get substituted appropriately in a rule's order-only inputs, but it does when present in the order-only inputs of a !-macro.

For example, the following will fail to compile:

```
: foreach *.c | %B.o |> echo %f %B.o |>
```

but by splitting it into a !-macro, it will:

```
!echo = | %B.o |> echo %f %B.o |>
: foreach *.c |> !echo |>
```

**Comment by skogshjort** [comment]
I ran into this today as well. Happy to have the work-around, but enabling the order-only inputs to depend on the current file makes sense to me.

My use case is working on file pairs, where I have a list of files, and each file have an associated file with changes to apply. The foreach construct doesn't allow (excuse the functional programming lingo) `zip`ing or similar, so doing a `: foreach $(files) | %B.changes |> apply_changes %f %B.changes |> %B.changed` would be a very nice solution.

**Comment by gittup** [comment]
I do get emails when issues are created/commented on, but I don't always have time to fix or respond to them. And I only rarely go back to look at old issues once they fall off my email radar. So pinging issues that are still bothering you may help, but is no guarantee :)

For this particular one, I do agree it's weird that there's different behavior here. I've added a test case for this and made a fix, but I wouldn't be surprised if it still needs some work. At least the example you posted should work now. Let me know if other cases aren't working as expected!
