### ISSUE TITLE
Generating tags using ctags for a C project with variants

### ISSUE THREAD

**Issue by kozross** [gittup/tup#311]
I have a C project with two variants (to build a release version and the tests respectively). My Tupfile thus looks something like this:

```
include_rules

ifdef TESTS
# stuff for tests
endif

ifdef RELEASE
# stuff for a release build
endif
```

However, I would also like to use ctags to make a tagfile for all my source code, and have that live in the project root (where it makes sense for it to be), and have that be maintained by tup. Can I actually do this somehow? As far as I can tell, this doesn't seem to be possible.

**Comment by renkam** [comment]
Take a look on this: https://groups.google.com/d/topic/tup-users/AfP0ouHRqGY/discussion
It is not exactly what you're asking, but might help.

**Comment by kozross** [comment]
Thanks - I solved my issue by simply not using variants.
