### ISSUE TITLE
List of dependencies

### ISSUE THREAD

**Issue by kingcocomango** [gittup/tup#314]
It would be cool if there was a list of dependencies that boostrapping tup from the repo needed, it would make it much easier to use it in docker images.

**Comment by kingcocomango** [comment]
Nevermind, apparently there's a bunch of issues getting fuse working even if all dependencies are satisfied.

**Comment by gittup** [comment]
The contrib/debian/control file has a list of dependencies for Debian packaging. Is that in a format that you can use? Or does it need to be a separate file?

And what issues are you having with getting fuse working in Docker?

**Comment by kingcocomango** [comment]
Ah, I didnt look into the sources.

That file covers some yeah, but the (debian based) container image also needed build-essential (and git and possibly makedev).

The fuse issue is in getting a dockerfile that builds an image that has tup, which isnt possible because there is no --privileged build option for docker, which is needed to use fuse, which tup needs to bootstrap itself. I got around it by using docker run + commit, and I'd like to point out this isnt an issue with tup at all, since using one of the tup repos works fine.

**Comment by gittup** [comment]
If I understand correctly, you can use tup with fuse inside the container, but you don't have access to fuse while creating the docker layer for tup by using bootstrap.sh, right? If so, we can probably make a separate bootstrap.sh that looks like this:

```
#! /bin/sh -e
CFLAGS="-g" ./build.sh

if [ ! -d .tup ]; then
	./build/tup init
fi
./build/tup generate build-nofuse.sh
./build-nofuse.sh
echo "Build complete. If ./tup works, you can remove the 'build' directory."
```

The generated tup executable still requires fuse, but that would avoid fuse during the boostrapping.

Does that work for you or am I missing something? If it does we can create it as bootstrap-nofuse.sh or something in the tup repo.

**Comment by kingcocomango** [comment]
Yup you understood correctly, I can use fuse and tup fine in a running container, but docker build does not have access to fuse which means I cant have a Dockerfile to build an image that builds tup with bootstrap.sh.

Yes, a bootstrap.sh that builds tup without requiring fuse solves my issue; Even when the tup it builds requires fuse.

**Comment by gittup** [comment]
Does the exact script I pasted above work for you? If so I'll check it in.

**Comment by kingcocomango** [comment]
Looking good on my end!
