### ISSUE TITLE
Handle NUL file on Windows

### ISSUE THREAD

**Issue by lindquist** [gittup/tup#321]
I have a linker that writes to NUL, which tup detects, but since this is the Windows equivalent of /dev/null, nothing is really written, it cannot be specified as an extra output either, since any attempt to manipulate it by tup fails.

It seems that to handle this, tup will need to know about this magic "file".

Information seems sparse, but here's something:
https://support.microsoft.com/en-us/help/40592/shell-redirected-to-nul-device-suppresses-ms-dos-message

**Comment by lindquist** [comment]
```
 *** tup errors ***
tup error: File 'nul' was written to, but is not in .tup/db. You probably should specify it as an output
 -- Delete: nul
 *** Command failed due to errors processing the output dependencies.
 [ ] 100%
 *** tup: 1 job failed.
```

**Comment by iology** [comment]
More magic names: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#naming_conventions

**Comment by gittup** [comment]
That's strange - tup is already supposed to be ignoring nul:

https://github.com/gittup/tup/blob/master/src/dllinject/dllinject.c#L1438

What linker are you using? Can you put together a small test case so that I can reproduce it?

**Comment by lindquist** [comment]
It's for Blackfin (Analog Devices DSP), the environment is commercial (Cross Core Embedded Studio), but there is a trial.

I was trying out tup to improve the Eclipse based builder which is horribly slow. It works great until the linking stage.

I can look at making a test case when I get back to work next week, but let me know if you're actually going to try it (ie. download the trial)

**Comment by gittup** [comment]
Ahh, thanks! I was able to reproduce it with ccblkfin.exe. Fortunately it also gets reproduced just by doing 'echo foo > NUL' in cmd.exe, so I've added a test case for it.

I have a demo version of CCES now, but it is only valid for 90 days I think. Let me know if you have further issues so that I can test them locally before it expires.

**Comment by lindquist** [comment]
It appears to be working well now. Thanks a bunch :-)

I will keep at it and let you know if anything comes up.
