### ISSUE TITLE
Strange Windows errors.

### ISSUE THREAD

**Issue by HaoZeke** [gittup/tup#337]
```bash
tup error: Failed to create child process: No such file or directory
```

This is the output when trying to run a command based on node-sass.

Node sass itself works on windows through the terminal.

I'm on windows 10, 64bit, the latest release from the master branch.

**Comment by cfillion** [comment]
Perhaps node-sass is a Batch script wrapper? If so, run it using cmd.exe: `cmd.exe /c node-sass ...`.

**Comment by HaoZeke** [comment]
Thanks, that worked perfectly!
