### ISSUE TITLE
Implicit dependencies do not account for changing directory contents

### ISSUE THREAD

**Issue by masaeedu** [gittup/tup#346]
Consider the following:

Tupfile:

```
: |> ./test.sh > %o |> contents.txt
```

test.sh:

```
ls .
```

Run `tup`. This creates the following `contents.txt`:

```
Tupfile
contents.txt
test.sh
```

Run `touch foo`, then `tup`. `contents.txt` remains unchanged, although there are now more files.

It seems like the correctness guarantees only hold for explicit dependencies; correctness wrt dependencies discovered via instrumentation still requires "clean builds".

**Comment by rulatir** [comment]
Maybe `opendir()`/`readdir()` aren't instrumented at all?
