### ISSUE TITLE
"A first tupfile" not working on windows

### ISSUE THREAD

**Issue by matanui159** [gittup/tup#364]

**Comment by matanui159** [comment]
Sorry, accidentally hit enter early.

I've got the file directory setup with `Tupfile.ini` and `hello.c` with the following contents:
```c
#include <stdio.h>

int main(void)
{
	printf("Hello, world!\n");
	return 0;
}
```
and
```
: hello.c |> gcc hello.c -o hello |> hello
```

Exactly copied from the tutorial, however when I run `tup` from within the directory:
```
PS C:\...\tup_test> tup
Initializing .tup in C:\Users\josh\Documents\vscode\tup_test
.tup repository initialized.
[ tup ] [0.016s] Scanning filesystem...
[ tup ] [0.033s] Reading in new environment variables...
[ tup ] [0.052s] Parsing Tupfiles...
 0) [0.002s] .
 [ ] 100%
[ tup ] [0.055s] No files to delete.
[ tup ] [0.074s] No commands to execute.
[ tup ] [0.075s] Updated.
```

I have also tried changing the `tup` file and deleting the `.tup` directory and it still doesn't build the file. I am using `tup v0.7.7-8-gf77dbd4` on Windows 10 64-bit.

**Comment by matanui159** [comment]
Ok I figured it out. For others who come across this issue, when it says to write in the "Tupfile", you gotta create a new file called `Tupfile` without the `.ini` extension instead of putting it in `Tupfile.ini`. This should probably be clarified better in the tutorial.

**Comment by tehKaiN** [comment]
It also confused me at start but thought it's just me, but now there's at least two of us. ;) This proves that rephrasing in docs is necessary, I think.

**Comment by tehKaiN** [comment]
It should also be noted that when using hello tup literally, as in:

``` tup
: hello.c |> gcc hello.c -o hello |> hello
```

you get:

```
[ tup ] [0.013s] Scanning filesystem...
[ tup ] [0.025s] Reading in new environment variables...
[ tup ] [0.036s] Parsing Tupfiles...
 0) [0.002s] .
 [ ] 100%
[ tup ] [0.039s] No files to delete.
[ tup ] [0.040s] Generating .gitignore files...
[ tup ] [0.049s] Executing Commands...
* 0) gcc hello.c -o hello
 *** tup messages ***
tup error: File 'C:/Users/tehKa/Desktop/tup/hello.exe' was written to, but is not in .tup/db. You probably should specify it as an output
 -- Delete: C:/Users/tehKa/Desktop/tup/hello.exe
tup error: Expected to write to file 'hello' from cmd 22 but didn't
 *** Command failed due to errors processing the output dependencies.
 [ ] 100%
 *** tup: 1 job failed.
```

because of .exe extension appended by GCC. One can either fix it by adding `.exe` to tup rule (also adding exe extension to builds on linux/osx) or using regex as supported in 0.7.8:

``` tup
: hello.c |> gcc hello.c -o hello |> ^hello(\.exe)?$
```

**Comment by nanoni17728** [comment]
Bumping this issue because I got into the same problem. The tutorial tells to write the tup rules in a `Tupfile.ini` but it doesn’t work on Windows, renaming the file `Tupfile` does the trick.

You should update your tutorial page to avoid new people getting into this problem.

**Comment by gittup** [comment]
Thanks for the bump, sorry I didn't get around to fixing this sooner.

**Comment by nanoni17728** [comment]
It’s alright. Thanks for your time :)
