### ISSUE TITLE
Version string messed up on Mac (Homebrew)

### ISSUE THREAD

**Issue by tomeksowi** [gittup/tup#384]
Tup 0.7.8 from [the Homebrew package](https://formulae.brew.sh/formula/tup#default) on MacOS Mojave 10.14.5 prints the version string as garbage:

    $ tup --version
    tup UH??H?.?
    $ tup --help
    tup UH??H?.? usage: tup [args]

I tried digging in a little, my tup binary built from Git tag `v0.7.8` shows the version fine:

    $ ./tup --version
    tup v0.7.8

The Homebrew binary doesn't have the "UH..." or "v0..." string in it but my build, of course, does:

    $ strings /usr/local/Cellar/tup/0.7.8/bin/tup | egrep "UH|v0"
    $ strings tup | egrep "UH|v0"
    v0.7.8

**Comment by tomeksowi** [comment]
Reinstalling the tup formula didn't help.

**Comment by gittup** [comment]
Thanks for filing this! Unfortunately I didn't notice the issue until updating the Homebrew package to v0.7.9 today, so this is still an issue there. However, it should work in the next version update.
