### ISSUE TITLE
foreach $a except $b

### ISSUE THREAD

**Issue by NieDzejkob** [gittup/tup#386]
Today, I wanted to build two executables: the main application, and a test runner. The test runner needs to include all objects from the main application, except main.

This is my `test/Tupfile`:

```
include_rules
CFLAGS += -lcriterion
: *.c | ../<nomain> |> gcc $(CFLAGS) %f %<nomain> -o %o |> test
```

Nothing too interesting here. Things get tricky with the main Tupfile. Obviously, this doesn't work:

```
: foreach *.c except main.c |> !cc |> gen/%B.o <nomain> {OBJS}
: main.c |> !cc |> gen/%B.o {OBJS}
```

However, I'm not aware of any other notation that would let me do this. I settled on using `run` to make bash generate a separate rule for each file, but I feel like this is common enough to be doable in Tup natively.

**Comment by tomeksowi** [comment]
I'm sure it can be done with a Lua Tupfile. But yeah, having a native option would be nice, even if by  a Lua inlay in an otherwise vanilla Tupfile (kind of an inline `include file`).

**Comment by NieDzejkob** [comment]
Potential workaround:

```

**Comment by gittup** [comment]
You can exclude with the ^, like this:

```
: foreach *.c ^main.c |> !cc |> gen/%B.o <nomain> {OBJS}
: main.c |> !cc |> gen/%B.o {OBJS}
```

The syntax is a little unfortunate, since a filename with a ^ has a different meaning in the output section (where it can be used to ignore reads & writes on files). In the input list like in this case it will cause tup to do a foreach loop on all c files, and skip main.c.

**Comment by NieDzejkob** [comment]
Huh, is this documented anywhere? I don't remember reading about anything like that. Or is that a new addition?

**Comment by gittup** [comment]
> Huh, is this documented anywhere? I don't remember reading about anything like that. Or is that a new addition?

Unfortunately it looks like it wasn't. I've updated the man page to describe it.
