### ISSUE TITLE
tup not identifying changes to input files, and not rebuilding (fedora 31)

### ISSUE THREAD

**Issue by speedyguy17** [gittup/tup#391]
Running into a situation where tup seems to fail to work at all in recent fedora

Environment:
 cat /etc/fedora-release
Fedora release 31 (Thirty One)

sudo dnf list installed | grep fuse
fuse.x86_64                                      2.9.9-8.fc31                           @fedora
fuse-common.x86_64                               3.6.2-1.fc31                           @fedora
fuse-devel.x86_64                                2.9.9-8.fc31                           @fedora
fuse-libs.x86_64                                 2.9.9-8.fc31                           @fedora
fuse3.x86_64                                     3.6.2-1.fc31                           @fedora
fuse3-libs.x86_64                                3.6.2-1.fc31                           @fedora
gvfs-fuse.x86_64                                 1.42.2-1.fc31                          @updates

Steps to reproduce:
> git clone git://github.com/gittup/tup.git
> cd tup
> ./build.sh
> sudo cp build/tup /usr/bin/tup
> which tup
>>> /usr/bin/tup
> tup init
> tup upd
>>> [ tup ] [32.526s] Updated.
> touch src/tup/*.c
> tup upd
>>>[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.229s] Reading in new environment variables...
[ tup ] [0.229s] No Tupfiles to parse.
[ tup ] [0.229s] No files to delete.
[ tup ] [0.230s] No commands to execute.
[ tup ] [0.326s] Updated.

EXPECTED: after touching all the sources, tup should ought to be rebuilding. I used the tup repo as an example, but it works with trivial examples as well:

[kevin@datadog ~/work/test] ls
test.sh  Tupfile
[kevin@datadog ~/work/test] cat test.sh
#! /bin/sh
echo "Hello"
[kevin@datadog ~/work/test] cat Tupfile
: |> ./test.sh > %o |> output.txt
[kevin@datadog ~/work/test] tup upd
[ tup ] [0.230s] Scanning filesystem...
[ tup ] [0.396s] Reading in new environment variables...
[ tup ] [0.486s] Parsing Tupfiles...
 0) [0.001s] .
 [ ] 100%
[ tup ] [0.498s] No files to delete.
[ tup ] [0.499s] Generating .gitignore files...
[ tup ] [0.606s] Executing Commands...
 0) [0.010s] ./test.sh > output.txt
 [ ] 100%
[ tup ] [0.714s] Updated.
[kevin@datadog ~/work/test] cat output.txt
Hello

Updates to test.sh are not picked up (following an edit to test.sh):

[kevin@datadog ~/work/test] cat test.sh
#! /bin/sh
echo "Goodbye"
[kevin@datadog ~/work/test] tup upd
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.182s] Reading in new environment variables...
[ tup ] [0.182s] No Tupfiles to parse.
[ tup ] [0.182s] No files to delete.
[ tup ] [0.182s] No commands to execute.
[ tup ] [0.278s] Updated.
[kevin@datadog ~/work/test] cat output.txt
Hello
[kevin@datadog ~/work/test]

It seems the tup is not correctly picking up the input dependency:

[kevin@datadog ~/work/test] tup graph .
digraph G {
        node_5 [label="test.sh\n5" shape="oval" color="#000000" fontcolor="#000000" style=solid];
        node_10 [label="output.txt\n10" shape="oval" color="#000000" fontcolor="#000000" style=solid];
        node_11 [label="./test.sh > output.txt\n11" shape="rectangle" color="#000000" fontcolor="#000000" style=solid];
        node_10 -> node_11 [dir=back,style="solid",arrowtail="empty"];
}

As nowhere is there a dependency on node_5, which is the shell script.

**Comment by gittup** [comment]
I tried this in a new fedora-31 VM, but I'm unable to reproduce it. What is particularly puzzling is that tup appears to see that the process is writing to the file (eg: output.txt in your second example), but is missing the file opened for reading. Since they should both go through the same FUSE fs, I'd expect either both or neither to be working.

Can you try the test.sh example again with --debug-fuse? Eg:

```
$ rm -rf .tup output.txt
$ tup init
$ tup upd --debug-fuse 2>fuse-log.txt
$ grep output.txt fuse-log.txt 
LOOKUP /@tupjob-12/home/marf/test/output.txt
getattr /@tupjob-12/home/marf/test/output.txt
create flags: 0x8241 /@tupjob-12/home/marf/test/output.txt 0100664 umask=0002
   create[12] flags: 0x8241 /@tupjob-12/home/marf/test/output.txt
getattr /@tupjob-12/home/marf/test/output.txt

$ grep test.sh fuse-log.txt 
LOOKUP /@tupjob-12/home/marf/test/test.sh
getattr /@tupjob-12/home/marf/test/test.sh
open flags: 0x8020 /@tupjob-12/home/marf/test/test.sh
   open[13] flags: 0x8020 /@tupjob-12/home/marf/test/test.sh
open flags: 0x8000 /@tupjob-12/home/marf/test/test.sh
   open[13] flags: 0x8000 /@tupjob-12/home/marf/test/test.sh
getattr /@tupjob-12/home/marf/test/test.sh
getattr /@tupjob-12/home/marf/test/test.sh
```

Maybe that will offer some clues.

**Comment by speedyguy17** [comment]
Many thanks for getting back to me on this. I grabbed the fuse log, and things APPEAR to be in order, and the output matches exactly yours, as one owuld expect

`[kevin@datadog ~/work/test] grep test.sh fuse-log.txt
LOOKUP /@tupjob-12/run/media/kevin/work/test/test.sh
getattr /@tupjob-12/run/media/kevin/work/test/test.sh
open flags: 0x8020 /@tupjob-12/run/media/kevin/work/test/test.sh
   open[13] flags: 0x8020 /@tupjob-12/run/media/kevin/work/test/test.sh
open flags: 0x8000 /@tupjob-12/run/media/kevin/work/test/test.sh
   open[13] flags: 0x8000 /@tupjob-12/run/media/kevin/work/test/test.sh
getattr /@tupjob-12/run/media/kevin/work/test/test.sh
getattr /@tupjob-12/run/media/kevin/work/test/test.sh
`
For completeness, I've attached the fuse-log in totality, which doesn't seem to indicate any issues, and shows the read occurring by the tup process
[fuse-log.txt](https://github.com/gittup/tup/files/4424694/fuse-log.txt)

Looking through the sql log, there is never an insertion of a normal link for the node:
[sql-log.txt](https://github.com/gittup/tup/files/4424717/sql-log.txt)


For completeness, here is a log with all the output togehter:
[output.txt](https://github.com/gittup/tup/files/4424729/output.txt)
and the associated graph from this run:
`digraph G {
        node_5 [label="log.txt\n5" shape="oval" color="#000000" fontcolor="#000000" style=solid];
        node_6 [label="test.sh\n6" shape="oval" color="#000000" fontcolor="#000000" style=solid];
        node_7 [label=".sql-log.txt.swp\n7" shape="oval" color="#000000" fontcolor="#000000" style=solid];
        node_12 [label="output.txt\n12" shape="oval" color="#000000" fontcolor="#000000" style=solid];
        node_13 [label="./test.sh > output.txt\n13" shape="rectangle" color="#000000" fontcolor="#000000" style=solid];
        node_12 -> node_13 [dir=back,style="solid",arrowtail="empty"];
}
`

Please let me know if there are any more data which might be helpful. Otherwise, if I get to it this weekend, I may dig into the source a bit, and see if I can narrow down where that link is getting lost.

**Comment by gittup** [comment]
Ahh, I think maybe the read is getting ignored because of the "/run" in the path: https://github.com/gittup/tup/blob/master/src/tup/server/fuse_fs.c#L302

The file writes are a handled a little differently with the path mapping, so that's why that part is working correctly. Maybe the "/run" ignore needs to be a little more targetted?

Can you try commented out that line in ignore_path and see if things start working?
