### ISSUE TITLE
tup FUSE failure on macOS 10.15.5

### ISSUE THREAD

**Issue by jwmerrill** [gittup/tup#395]
**Version info:**
macOS: 10.15.5 (19F101)
tup: 0.7.8 (installed with homebrew)
osxfuse: 3.10.4, 3.10.5

When I run `tup` on the example project from [A First Tupfile](http://gittup.org/tup/ex_a_first_tupfile.html), I see the following output:

```
> tup
[ tup ] [0.001s] Scanning filesystem...
[ tup ] [0.003s] Reading in new environment variables...
[ tup ] [0.005s] Parsing Tupfiles...
fuse: writing device: Socket is not connected
tup error: FUSE file-system does not appear to be mounted properly.
```

It takes a few minutes after "Parsing Tupfiles..." to get to the error output. The error output appears to come from 

https://github.com/gittup/tup/blob/4aee2f7e1eda1fa2732d1d52f4f585e9ec54c648/src/tup/server/fuse_server.c#L293-L321

where `tup` is polling for access to a special file.

## Notes

I had initially installed osxfuse 3.10.4 through homebrew cask, but I tried uninstalling that and installing [osxfuse 3.10.5](https://osxfuse.github.io/2020/05/27/OSXFUSE-3.10.5.html) (currently a developer preview). That version also exhibits this problem.

I also tried installing `sshfs` to test whether my `osxfuse` installation was working at all, and I was able to successfully mount and read/write a directory on a separate machine. I think that's evidence that `osxfuse` is at least basically functional in this configuration.

Two of my coworkers also recently upgraded to macOS 10.15.5 and are also experiencing this problem.

**Comment by gittup** [comment]
Thanks for the detailed report! This problem appears to be specific to 10.15, and unfortunately my OSX test machine is stuck on 10.11, so I haven't seen this locally. The fix seems to be pretty straightforward - can you try to build tup from the latest master and make sure it works for you? I've verified that it can build & run all tests on 10.15 now.

**Comment by pinver** [comment]
Confirmed working on 10.15 with the latest master, thank you for the quick fix!

**Comment by jwmerrill** [comment]
Working for me too. Thanks so much!
