### ISSUE TITLE
tup error: FUSE file-system does not appear to be mounted properly.

### ISSUE THREAD

**Issue by Peter-haotian-cui** [gittup/tup#396]
Hi, 
Several days ago, my MacOS upgrade to the new version 10.15.5. A project (https://github.com/madcowswe/ODrive) uses tup cannot be build and I got 
```
$ make
fuse: writing device: Socket is not connected
tup error: FUSE file-system does not appear to be mounted properly.
make: *** [all] Error 1
```
error message. Is there any released version of tup that solved this problem?

**Comment by gittup** [comment]
This sounds like a dupe of #395 - can you test tup from git and see if that fixes the problem?

**Comment by Peter-haotian-cui** [comment]
Thanks, I just follow the instruction of "http://gittup.org/tup/" and build a new tup and replace the executable file under /usr/local/Cellar/tup/0.7.8/bin. It worked! It would be convenient to have a "brew update" command to do this.

**Comment by gittup** [comment]
The brew package should now be updated to 0.7.9 - can you try to update from there and make sure things are working?

**Comment by Peter-haotian-cui** [comment]
The " brew upgrade tup " worked, thanks!
