### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by ryandesign** [gittup/tup#398]
tup fails to build:

```
  bootstrap LD tup -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -lm
fatal: not a git repository (or any of the parent directories): .git
```

This is because of f9000d1ac10ec014cd3e6d9f6d665bd2bbdc2666 which modified the build process to use link.sh, which calls `git describe`, which of course doesn't work, since I am not building in a git clone. (I have downloaded a tarball instead.)

**Comment by gittup** [comment]
Thanks for the report! Can you test with the latest and verify that it's working now?

**Comment by ryandesign** [comment]
Yup, that works. Thank you!
