### ISSUE TITLE
bootstrap-nofuse.sh: "fatal: Not a git repository"

### ISSUE THREAD

**Issue by leek2** [gittup/tup#399]
I've had this problem with 0.7.8 and 0.7.9 releases.  I couldn't get boostrap.sh to work due to some kind of fuse issue.  So I tried bootstrap-nofuse.sh.  It gets quite far, and then stops with this "Not a git repository" error.  I downloaded a release tarball, so it's true it's not a git repository.

It did work properly from a cloned repo.  It just seems like releases should work.

-----
+ gcc -c sqlite3.c -o sqlite3.o -Os -g -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -I../../src -D_FILE_OFFSET_BITS=64 -w -DSQLITE_TEMP_STORE=2 -DSQLITE_THREADSAFE=0 -DSQLITE_OMIT_LOAD_EXTENSION
+ cd ../inih
++ pcre-config --cflags
+ gcc -c ini.c -o ini.o -Os -g -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -I../../src -D_FILE_OFFSET_BITS=64 -Wno-cast-qual -DINI_ALLOW_MULTILINE=0
+ cd ../..
+ ar crs libtup_client.a src/tup/vardict.o src/tup/send_event.o src/tup/flock/fcntl.o
+ cp src/tup/vardict.h tup_client.h
++ pcre-config --cflags
++ pcre-config --libs
++ pkg-config fuse --libs
+ ./src/tup/link.sh gcc '-Os -g -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch-enum -fno-common -I./src  -D_FILE_OFFSET_BITS=64' '-lpcre -pthread -lfuse   -lm -lpthread' tup 'src/tup/bin.o src/tup/ccache.o src/tup/colors.o src/tup/config.o src/tup/create_name_file.o src/tup/db.o src/tup/debug.o src/tup/delete_name_file.o src/tup/dircache.o src/tup/entry.o src/tup/environ.o src/tup/estring.o src/tup/file.o src/tup/fslurp.o src/tup/graph.o src/tup/if_stmt.o src/tup/init.o src/tup/lock.o src/tup/logging.o src/tup/luaparser.o src/tup/option.o src/tup/parser.o src/tup/path.o src/tup/pel_group.o src/tup/platform.o src/tup/progress.o src/tup/send_event.o src/tup/string_tree.o src/tup/thread_tree.o src/tup/timespan.o src/tup/tupid_tree.o src/tup/updater.o src/tup/vardb.o src/tup/vardict.o src/tup/variant.o src/tup/varsed.o src/tup/tup/main.o src/tup/monitor/inotify.o src/tup/flock/fcntl.o src/tup/server/fuse_fs.o src/tup/server/fuse_server.o src/tup/server/master_fork.o src/inih/ini.o src/compat/dummy.o src/compat/utimensat_linux.o src/sqlite3/sqlite3.o src/lua/liblua.a'
fatal: Not a git repository (or any parent up to mount point /home/leek2)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by gittup** [comment]
Thanks for the report! I've added some integration tests to hopefully catch stuff like this in the future, and the commit above should fix it for the next release.
