### ISSUE TITLE
tup internal error: create_ignored_file() didn't get a final pel pointer for file

### ISSUE THREAD

**Issue by fraespre** [gittup/tup#400]
Hello

I'm using the 0.79 version of Tup for Windows.

I have an internal error when I try to ignore an output file. I suspect this is because this file is out of the project folder.

This is macro where it's defined:
`!objlink= |> ^ Linking => %o^ zcc $(LFLAGS) %<objs> -o $(TAPELB) |> $(TAPELB).tap ^zx_crt.asm`

The internal error is the follow:
`tup info: Ignoring file 'C:/mio/soft/dev/z80/z88dk-2.0/libsrc/_DEVELOPMENT/target/zx/zx_crt.asm' because it matched the regex 'zx_crt.asm'`
`tup internal error: create_ignored_file() didn't get a final pel pointer for file: C:/mio/soft/dev/z80/z88dk-2.0/libsrc/_DEVELOPMENT/target/zx/zx_crt.asm`

Thanks in advanced

**Comment by gittup** [comment]
Thanks for the report! It looks like this was also reported in #375, which was merged a few months after this was filed. This should be working in v0.7.10 and later.
