### ISSUE TITLE
tup don't detect changes in the files (windows)

### ISSUE THREAD

**Issue by fraespre** [gittup/tup#401]
Hello

I'm using the 0.79 version of Tup for Windows.

Well, I test that Tup can detect the new files that appear in the project folders. And the same when I delete any file.
But it's very strange for me that Tup can't detect changes in the file. I tried for example "echo 'new line' >> file.c , and nothing it happended.

( of course, the "tup init" command has already been run previously. It's obvious )

> _C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1>tup
> [ tup ] [0.000s] Scanning filesystem...
> [ tup ] [0.016s] Reading in new environment variables...
> [ tup ] [0.016s] No Tupfiles to parse.
> [ tup ] [0.022s] No files to delete.
> [ tup ] [0.022s] No commands to execute.
> [ tup ] [0.022s] Updated._

> _C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1>echo 'new line' >> src\Main.c_

(I check that of course the file has a new line)

> _C:\mio\soft\dev\z80\wrks\zxspectrum\batsp1>tup
> [ tup ] [0.000s] Scanning filesystem...
> [ tup ] [0.053s] Reading in new environment variables...
> [ tup ] [0.053s] No Tupfiles to parse.
> [ tup ] [0.069s] No files to delete.
> [ tup ] [0.069s] No commands to execute.
> [ tup ] [0.100s] Updated._

I start to suspect if I haven't install correctly the tool.

Can you help me to find out what does it work wrong?

**Comment by Dmole** [comment]
Run `tup init`

    No Tupfiles to parse.

indicates you should read this http://gittup.org/tup/ex_a_first_tupfile.html and close this issue.

**Comment by fraespre** [comment]
OK @Dmole ,

I get your "tutorial" ( http://gittup.org/tup/ex_a_first_tupfile.html ).
I follow step by step:

step 1

> C:\mio\tmp>cd tup_test
> 
> C:\mio\tmp\tup_test>dir
>  El volumen de la unidad C es OS
>  El número de serie del volumen es: FC87-45BD
> 
>  Directorio de C:\mio\tmp\tup_test
> 
> 02/07/2020  23:51    <DIR>          .
> 02/07/2020  23:51    <DIR>          ..
>                0 archivos              0 bytes
>                2 dirs  71.449.018.368 bytes libres

step 2

> C:\mio\tmp\tup_test>tup init
> .tup repository initialized.

step 3

(I introduce the indicated file using a notepad of Windows) 

> C:\mio\tmp\tup_test>type hello.c
> #include <stdio.h>
> 
> int main(void)
> {
>         printf("Hello, world feo!\n");
>         return 0;
> }
> 
> C:\mio\tmp\tup_test>type Tupfile
> : hello.c |> echo 'fofofo' > hello |> hello

( well , It is not the same rule of the tutorial, because I do not have the gcc installed, but I think that to demonstrate the issue it can be useful, right? ) 

step 4

> C:\mio\tmp\tup_test>dir
>  El volumen de la unidad C es OS
>  El número de serie del volumen es: FC87-45BD
> 
>  Directorio de C:\mio\tmp\tup_test
> 
> 02/07/2020  23:55    <DIR>          .
> 02/07/2020  23:55    <DIR>          ..
> 02/07/2020  23:54    <DIR>          .tup
> 02/07/2020  23:44                93 hello.c
> 02/07/2020  23:36                43 Tupfile
>                2 archivos            136 bytes
>                3 dirs  71.392.317.440 bytes libres

step 5

> C:\mio\tmp\tup_test>tup
> [ tup ] [0.031s] Scanning filesystem...
> [ tup ] [0.078s] Reading in new environment variables...
> [ tup ] [0.100s] Parsing Tupfiles...
>  0) [0.000s] .
>  [ ] 100%
> [ tup ] [0.100s] No files to delete.
> [ tup ] [0.100s] Generating .gitignore files...
> [ tup ] [0.132s] Executing Commands...
>  0) [0.047s] echo 'fofofo' > hello
>  [ ] 100%
> [ tup ] [0.216s] Updated.

step 6

> C:\mio\tmp\tup_test>dir
>  El volumen de la unidad C es OS
>  El número de serie del volumen es: FC87-45BD
> 
>  Directorio de C:\mio\tmp\tup_test
> 
> 03/07/2020  00:01    <DIR>          .
> 03/07/2020  00:01    <DIR>          ..
> 03/07/2020  00:01    <DIR>          .tup
> 03/07/2020  00:01                11 hello
> 02/07/2020  23:44                93 hello.c
> 02/07/2020  23:36                43 Tupfile
>                3 archivos            147 bytes
>                3 dirs  71.391.363.072 bytes libres

step 7

> C:\mio\tmp\tup_test>tup
> [ tup ] [0.000s] Scanning filesystem...
> [ tup ] [0.000s] Reading in new environment variables...
> [ tup ] [0.000s] No Tupfiles to parse.
> [ tup ] [0.000s] No files to delete.
> [ tup ] [0.016s] No commands to execute.
> [ tup ] [0.016s] Updated.

step 8

> C:\mio\tmp\tup_test>echo new line >> hello.c
> 
> C:\mio\tmp\tup_test>type hello.c
> #include <stdio.h>
> 
> int main(void)
> {
>         printf("Hello, world feo!\n");
>         return 0;
> }
> 
> new line

step 9

> C:\mio\tmp\tup_test>tup
> [ tup ] [0.000s] Scanning filesystem...
> [ tup ] [0.031s] Reading in new environment variables...
> [ tup ] [0.031s] No Tupfiles to parse.
> [ tup ] [0.031s] No files to delete.
> [ tup ] [0.031s] No commands to execute.
> [ tup ] [0.069s] Updated.

**THIS is the problem: TUP don't detect that the file has changed !!!**

The rest of the tutorial is OK, included the part where you change the rule and tup detect the modification into the Tupfile.

**Comment by fraespre** [comment]
I have seen a similar issue: https://github.com/gittup/tup/issues/364

**Comment by gittup** [comment]
> > No Tupfiles to parse.

All this message means is that no Tupfiles (or dependent files) have changed since the last time tup was run, so no Tupfiles need to be parsed. It doesn't mean there are no Tupfiles at all under the tup hierarchy, or that the build is empty. In other words, they could have set up the build or followed the example correctly and done one build already, but a subsequent build doesn't need to re-parse the Tupfiles.

> > C:\mio\tmp\tup_test>type Tupfile
> > : hello.c |> echo 'fofofo' > hello |> hello
> 
> ( well , It is not the same rule of the tutorial, because I don't have the gcc installed, but I think that to demonstrate the issue it can be useful, right? )

Although on the surface I can see why you would think this change would mimic what gcc does, it doesn't actually read the files like gcc would have done, and therefore does not get the dependencies on them. In tup, an input file, like 'hello.c' in this case, does *not* necessarily mean that it will re-run the command if the input file changes. All it means is that *if* the input file needs to be rebuilt, it will be done before this command runs.

Tup instruments the running command and detects what files it actually reads from to determine the set of files that will cause the command to re-run. Since the echo command did not read from hello.c, changing hello.c will not cause the output to change. Therefore, tup can skip the command. If however your rule reads from hello.c, then you'll see it update properly:

```
C:\testdir>cat Tupfile
: hello.c |> cat hello.c > hello |> hello

C:\testdir>tup
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.016s] Reading in new environment variables...        
[ tup ] [0.016s] No Tupfiles to parse.
[ tup ] [0.016s] No files to delete.
[ tup ] [0.016s] No commands to execute.      
[ tup ] [0.016s] Updated.       

C:\testdir>echo new line >> hello.c
C:\testdir>tup
[ tup ] [0.000s] Scanning filesystem...   
[ tup ] [0.203s] Reading in new environment variables...
[ tup ] [0.203s] No Tupfiles to parse.
[ tup ] [0.203s] No files to delete.
[ tup ] [0.203s] Executing Commands...
 0) [0.062s] cat hello.c > hello
 [ ] 100%
[ tup ] [0.438s] Updated.
```

Can you confirm that changing from an echo to 'cat hello.c' works as expected?

**Comment by fraespre** [comment]
Sorry @gittup  , but the "cat" command doesn't exist in Windows shell.

However I've modified the tutorial example to be quite similar to my real case (it's a simplification). I hope it's valid for you.

> C:\mio\tmp\tup_test>dir
>  El volumen de la unidad C es OS
>  El número de serie del volumen es: FC87-45BD
> 
>  Directorio de C:\mio\tmp\tup_test
> 
> 03/07/2020  08:11    <DIR>          .
> 03/07/2020  08:11    <DIR>          ..
> 03/07/2020  08:10                69 hello.c
> 03/07/2020  08:09               179 Tupfile
>                2 archivos            248 bytes

> C:\mio\tmp\tup_test>type hello.c
> #include <stdio.h>
> 
> void main() {
>   uint8_t x;
> 
>   x= 0;
> }

> C:\mio\tmp\tup_test>type Tupfile
> export ZCCCFG
> 
> CFLAGS= +zx -v -preserve -startup=31 -clib=sdcc_iy
> 
> !compile= |> ^ Compile %f^ zcc $(CFLAGS) -c %f -o %o |>
> 
> : hello.c |> !compile |> hello.o ^zcc_opt.def

( This time I'm going to use the z88dk compiler, this is my real scenario but using one simiplified rule )

> C:\mio\tmp\tup_test>tup init
> .tup repository initialized.

> C:\mio\tmp\tup_test>tup
> [ tup ] [0.022s] Scanning filesystem...
> [ tup ] [0.053s] Reading in new environment variables...
> [ tup ] [0.069s] Parsing Tupfiles...
>  0) [0.000s] .
>  [ ] 100%
> [ tup ] [0.085s] No files to delete.
> [ tup ] [0.085s] Generating .gitignore files...
> [ tup ] [0.123s] Executing Commands...
>  0) [1.053s] Compile hello.c
> 
> PROCESSING hello.c
> zsdcpp -iquote"." -D__Z88DK -D__SPECTRUM -DSPECTRUM -D__SPECTRUM__ -D__Z80 -DZ80 -D__SDCC -D__SDCC_IY -isystem"C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\\include\_DEVELOPMENT\sdcc"  -D__SDCC  "hello.c" "C:\Users\javi\AppData\Local\Temp\zccCE8A2.i2"
> z88dk-zpragma  < "C:\Users\javi\AppData\Local\Temp\zccCE8A2.i2" > "C:\Users\javi\AppData\Local\Temp\zccCE8A2.i"
> zsdcc --constseg rodata_compiler   --reserve-regs-iy -mz80 --no-optsdcc-in-asm --c1mode --emit-externs  --no-c-code-in-asm   --no-peep --peep-file "C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\/libsrc/_DEVELOPMENT/sdcc_peeph.2"  < "C:\Users\javi\AppData\Local\Temp\zccCE8A2.i" -o "C:\Users\javi\AppData\Local\Temp\zccCE8A2.opt"
> z88dk-copt  "C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\/libsrc/_DEVELOPMENT/sdcc_opt.1" < "C:\Users\javi\AppData\Local\Temp\zccCE8A2.op1" > "C:\Users\javi\AppData\Local\Temp\zccCE8A2.opt"
> z88dk-copt  "C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\/libsrc/_DEVELOPMENT/sdcc_opt.9" < "C:\Users\javi\AppData\Local\Temp\zccCE8A2.opt" > "C:\Users\javi\AppData\Local\Temp\zccCE8A2.op1"
> z88dk-copt  "C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\/libsrc/_DEVELOPMENT/sdcc_opt.2" < "C:\Users\javi\AppData\Local\Temp\zccCE8A2.op1" > "C:\Users\javi\AppData\Local\Temp\zccCE8A2.asm"
> type "C:\Users\javi\AppData\Local\Temp\zccCE8A2.asm" >> "C:\Users\javi\AppData\Local\Temp\zccCE8A2.tmp"
> type "C:\Users\javi\AppData\Local\Temp\zccCE8A2.tmp" >> "C:\Users\javi\AppData\Local\Temp\zccCE8A2.asm"
> z80asm -I"C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\\lib\target\zx\def" -D__SDCC_IY -I"C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\\libsrc\_DEVELOPMENT\target\zx" -D__SDCC  -s  -mz80 -I"C:\mio\soft\dev\z80\z88dk-2.0\lib\config\..\..\/lib" "C:\Users\javi\AppData\Local\Temp\zccCE8A2.asm"
> 
> GENERATING OUTPUT
> type "C:\Users\javi\AppData\Local\Temp\zccCE8A2.o" >> "hello.o"
>  [ ] 100%
> [ tup ] [1.207s] Updated.

> C:\mio\tmp\tup_test>dir
>  El volumen de la unidad C es OS
>  El número de serie del volumen es: FC87-45BD
> 
>  Directorio de C:\mio\tmp\tup_test
> 
> 03/07/2020  08:22    <DIR>          .
> 03/07/2020  08:22    <DIR>          ..
> 03/07/2020  08:22    <DIR>          .tup
> 03/07/2020  08:10                69 hello.c
> 03/07/2020  08:22               227 hello.o
> 03/07/2020  08:09               179 Tupfile
> 03/07/2020  08:22               104 zcc_opt.def
>                4 archivos            579 bytes

( so far so good )

> C:\mio\tmp\tup_test>tup
> [ tup ] [0.000s] Scanning filesystem...
> [ tup ] [0.031s] Reading in new environment variables...
> [ tup ] [0.031s] No Tupfiles to parse.
> [ tup ] [0.031s] No files to delete.
> [ tup ] [0.031s] No commands to execute.
> [ tup ] [0.047s] Updated.

( I modify the hello.c with Notepad editor )

> C:\mio\tmp\tup_test>type hello.c
> #include <stdio.h>
> 
> void main() {
>   uint8_t x;
> 
>   x= 0;
>   x++;
> }

> C:\mio\tmp\tup_test>dir
>  El volumen de la unidad C es OS
>  El número de serie del volumen es: FC87-45BD
> 
>  Directorio de C:\mio\tmp\tup_test
> 
> 03/07/2020  08:22    <DIR>          .
> 03/07/2020  08:22    <DIR>          ..
> 03/07/2020  08:25    <DIR>          .tup
> 03/07/2020  08:27                77 hello.c
> 03/07/2020  08:22               227 hello.o
> 03/07/2020  08:09               179 Tupfile
> 03/07/2020  08:22               104 zcc_opt.def
>                4 archivos            587 bytes

( the hello.c file has been modified: the content, the size and the last modified time )
You have noticed that:
`03/07/2020  08:10   69 hello.c` ==> `03/07/2020  08:27   77 hello.c`

> C:\mio\tmp\tup_test>tup
> [ tup ] [0.000s] Scanning filesystem...
> [ tup ] [0.031s] Reading in new environment variables...
> [ tup ] [0.031s] No Tupfiles to parse.
> [ tup ] [0.031s] No files to delete.
> [ tup ] [0.047s] No commands to execute.
> [ tup ] [0.063s] Updated.

( but tup doesn't detect that the file has changed )

**Comment by gittup** [comment]
Ahh, thanks for the info! I'm able to reproduce the issue you're seeing with the z88dk compiler. The problem appears to be that zcc.exe is a 32-bit application, while zsdcpp.exe (which is the subprocess that reads from hello.c, and would cause tup to generate the dependency) is a 64-bit application. I'm not too familiar with the underlying DLL injection mechanism that tup uses since it was written by other contributors, but it looks like going from 32-bit back to a 64-bit process is not supported (or at least not implemented). I was able to confirm that running zsdcpp.exe directly to create a .i file from your hello.c file works as expected - changing hello.c re-runs zsdcpp.exe.

Any idea if it's possible to change zcc.exe to be 64-bit? Going from 64-bit to 32-bit applications is fine, but the reverse does not work at the moment. If not, I'll have to solicit help from those who are more knowledgeable in this area :)

**Comment by fraespre** [comment]
hi @gittup ,
Thanks a lot for your investigation. I guess that it hasn't been easy.

I haven't checked the confirmation you requested, because I have seen that the other executables related with zcc, as zsdcpp or zsdcc are 32-bits compiled too.

However, I have done the test using the Windows command line based in 64-bits (C:\Windows\SysWOW64\cmd.exe) and after I have sustituted the zcc compiler by an internal command, specifically `more` :

> !compile= |> ^ Compile %f^ more %f > %o |>

And the result it's clear, in this scenario tup works fine.

Well, if nothing changes, I suppouse that you should document this limitation for Windows. And I will try to get a 64-bits compiled version of the z88dk  :-D

Kind regards and thanks again,

**Comment by gittup** [comment]
> hi @gittup ,
> Thanks a lot for your investigation. I guess that it hasn't been easy.
> 
> I haven't checked the confirmation you requested, because I have seen that the other executables related with zcc, as zsdcpp or zsdcc are 32-bits compiled too.

Oh, they are? What version of z88dk are you using? I grabbed 2.0 and using sigcheck.exe from sysinternals I see this:
```
$ sigcheck zcc.exe
        ...
        MachineType:    32-bit

$ sigcheck zsdcpp.exe
        ...
        MachineType:    64-bit
```
