### ISSUE TITLE
setpgid: Operation not permitted

### ISSUE THREAD

**Issue by NieDzejkob** [gittup/tup#403]
Some tools, such as [watchexec](https://github.com/watchexec/watchexec), already launch commands in a separate process group.

This results in the error `setpgid: Operation not permitted`, as `tup` is already the session leader.

Workaround: instruct tools to run `sh -c 'tup;:'` instead. That way, the shell becomes the session leader, and tup can detach itself from the process group again.

Relevant versions:
tup 0.7.9
Linux 5.4.50

**Comment by ppannuto** [comment]
Is this fixed for you in latest master? Specifically https://github.com/gittup/tup/pull/349 may already address this.

**Comment by NieDzejkob** [comment]
Sorry, for some reason I didn't think to test `master`. BTW, do you have any plans for when the next version would be released?
