### ISSUE TITLE
Feature request: transient outputs

### ISSUE THREAD

**Issue by sboukortt** [gittup/tup#405]
Hi,

First of all, I would like to thank you for such a great and useful tool.

It occurred to me that a feature that would perhaps make it even more useful would be if it were possible to indicate that a given output can be deleted once all the targets that depend on it have been produced. It could look like this for example:

~~~bash
: input.txt |> ^t^ cp %f %o |> intermediate.txt
#              ~~~

: intermediate.txt |> cp %f %o |> output.txt

: output.txt |> cp %f %o |> output-copy.txt
~~~

`tup` would then, like it currently does:

1. run `cp input.txt intermediate.txt`
2. run `cp intermediate.txt output.txt`
3. run `cp output.txt output-copy.txt`

but in addition, after 2 or 3 (ideally as soon as possible), it would also delete `intermediate.txt` from the filesystem, without it counting as being “deleted outside of tup”, therefore it (and the rules that transitively depend on it) would not be rebuilt merely for that reason. Only a change to its inputs (including its rule), or the execution of a rule that directly depend on it, would cause the file to be rebuilt (and then deleted again).

The use for this would mainly be to free disk space: I currently have a tup pipeline where I split a video file into individual frames, and then each frame into tiles, and once that is done, I don’t need the whole frames anymore, but they still take up gigabytes of space.

Thanks.

**Comment by rulatir** [comment]
Abandon any hope that Tup's author will ever make even the slightest compromise sacrificing merciless pedantic correctness in favor of expressive power. Not happening, trust me.

**Comment by gittup** [comment]
> Abandon any hope that Tup's author will ever make even the slightest compromise sacrificing merciless pedantic correctness in favor of expressive power. Not happening, trust me.

While your criticism is probably valid for other reasons, in this case the feature is just hard to implement. In particular, it is difficult to make sure that tup is rebuilding everything when necessary, removing the transient files as soon as it is able to, and not wasting time doing unnecessary work (ie: the "merciless pedantic correctness" that makes tup useful in the first place).

@sboukortt, can you try https://github.com/gittup/tup/tree/transient-outputs-db18 and see if the ^t flag works as you'd expect? If you come across and oddities and can come up with a small test case to reproduce, that would be helpful as well. Note that this branch updates the database, so if you want to go back to a different version of tup, you'll need to `mv .tup/db_backup_17 .tup/db` in order to revert the db. (This will then cause a single spurious rebuild, as the old database won't have the correct timestamps for anything you've done in the meantime).

**Comment by sboukortt** [comment]
Wow, thank you for implementing this!

It does seem to work for the most part, however I did encounter a case where this happened:

```
unlinkat: No such file or directory
tup error: Unable to unlink transient output file: frame-009.png
```

And indeed, this seems to have occurred before the command that generated `frame-009.png` was run. The file now exists on disk, but subsequent attempts to run tup have it deadlock at this location:

```
#0  0x000055555558ae24 in tupid_entries_RB_REMOVE (head=head@entry=0x7fffffffe120, elm=0x55555574cb88, elm@entry=0x55555574cad8) at tupid_tree.c:31
#1  0x0000555555578df4 in tupid_tree_rm (tt=0x55555574cad8, root=0x7fffffffe120) at tupid_tree.h:48
#2  remove_node (g=g@entry=0x7fffffffe0d0, n=n@entry=0x55555574cab8) at graph.c:107
#3  0x00005555555791ee in remove_node_internal (g=g@entry=0x7fffffffe0d0, n=0x55555574cab8) at graph.c:96
#4  0x000055555557a393 in attach_transient_nodes (g=g@entry=0x7fffffffe0d0) at graph.c:451
#5  0x000055555557a618 in build_graph (g=g@entry=0x7fffffffe0d0) at graph.c:502
#6  0x000055555558e0bf in process_update_nodes (argc=argc@entry=0, argv=argv@entry=0x7fffffffe320, num_pruned=num_pruned@entry=0x7fffffffe1a4) at updater.c:1440
#7  0x0000555555590618 in updater (argc=0, argc@entry=1, argv=0x7fffffffe320, argv@entry=0x7fffffffe318, phase=phase@entry=0) at updater.c:208
#8  0x00005555555949b4 in main (argc=1, argv=0x7fffffffe318) at main.c:219
```

When this happened, `frame-009.png` was a transient file generated from five other transient files. I am not sure to what extent this played a part.

(Also, unrelated to this, changing a file from permanent to transient seems to trigger a rebuild but this probably doesn’t matter much.)

**Comment by gittup** [comment]
I wasn't able to reproduce your issue exactly, though I did catch a few odd errors while trying to do so. Some of the issues resulted in messing up lists of nodes in the graph, which created bizarre side effects. I'm not sure if what you saw was one of these side effects or something else, though. Can you try again with the latest of that branch?

**Comment by gittup** [comment]
@sboukortt Any feedback here? I'd like to merge this if the latest version fixes the issues you were hitting and works as expected.

**Comment by sboukortt** [comment]
Sorry for the delay in responding. I don’t remember with certainty whether I encountered problems again. I think I might have but I wished to investigate in what kind of scenario they occurred, or maybe I didn’t but wanted to test it more deeply before declaring victory. Either way, it then somehow drifted off my plate.

Trying now, the problem doesn’t seem to be reoccurring, and the feature is very effective at saving disk space, as hoped. Thanks again!
