### ISSUE TITLE
`generate` subcommand deadlocks on `run` rule

### ISSUE THREAD

**Issue by Crystalix007** [gittup/tup#408]
Hi,

I've been trying to get Tup to generate a build script for a Tupfile involving a `run` command. I.e. running `tup generate build.sh` on:

```
# Tupfile

run ./script.sh
```

where `script.sh` is anything, such as:

```
# script.sh

#!/usr/bin/env sh

printf ''
```

However, it never manages to progress beyond the printing of the command and the environment. Doing a bisect on `tup`, this doesn't seem to have ever worked (at least since the `generate` command existed).

I added loads of print statements everywhere, and the first difference between `tup upd` and `tup generate build.sh` seems to be [`read_all_internal`](https://github.com/gittup/tup/blob/master/src/tup/server/master_fork.c#L325) (Line 325 is the first print label I see).

The main thread is deadlocking on the `pthread_cond_wait` call in [`wait_for_my_sid`](https://github.com/gittup/tup/blob/master/src/tup/server/master_fork.c#L825). I'm not sure how this signal is supposed to be sent, as neither `generate` nor `upd` seems to run the [`master_fork_loop`](https://github.com/gittup/tup/blob/master/src/tup/server/master_fork.c#L719) which is the only place I see the condition being signalled, so not sure how to fix this myself.

### Edit

Adding a `tup_init` call before the `generate` call prevents the deadlocking, however, it stills seems that the environment is not fully configured, as tup errors with:

```
.tup/tmp/output-1: No such file or directory
tup error: Unable to create temporary file for sub-process output.
```

**Comment by gittup** [comment]
Your fixes in #409 seem to have addressed this. Thanks for your help!
