### ISSUE TITLE
-h/--help on "tup init" creates a directory

### ISSUE THREAD

**Issue by EV3R4** [gittup/tup#420]
I don't think that "tup init -h" or "tup init --help" should create a directory.
(maybe even completely disable the creation of directories starting with a minus)

**Comment by gittup** [comment]
Agreed, that should just print out help info. I've added that for all the secondary commands described in the man page, but it's not exhaustive yet. At least, 'tup init -h' now prints out some help info rather than creating a '-h' directory.
