### ISSUE TITLE
tup dbconfig requires an (arbitrary) argument

### ISSUE THREAD

**Issue by petemoore** [gittup/tup#422]
Hey Mike!

I started having a play with `tup` today, and was working my way through the manual. Am I doing something wrong here(?), I seem to need to pass a single additional (arbitrary) argument to `tup dbconfig`:

```
pmoore@fedora:~/git/spectrum4 master $ tup dbconfig # expected this to be successful as no additional args were passed
tup error: 'dbconfig' doesn't take arguments.
pmoore@fedora:~/git/spectrum4 master $ tup dbconfig vbvbvb # expected this to have the above error, but is successful
db_version: '18'
parser_version: '15'
pmoore@fedora:~/git/spectrum4 master $ tup dbconfig vbvbvb sdfsdf # passing 2 args doesn't work, as expected
tup error: 'dbconfig' doesn't take arguments.
pmoore@fedora:~/git/spectrum4 master $ 
```

Everything else has been plain sailing so far with no issues! :-) Loving the project!

**Comment by gittup** [comment]
Oops, this probably broke a little while back when I changed the argc/argv handling. I don't think it gets much use, but it should ignore arguments now. Thanks for the report!
