### ISSUE TITLE
can't install tup on macos

### ISSUE THREAD

**Issue by satishgaurav** [gittup/tup#461]
I am not able to install tup on macOS. I tried installing it in two ways: 
1. `brew install tup` : 
I get the following error: 
Error: tup has been disabled because it requires closed-source macFUSE!
I have macFUSE installed on my computer. 

<img width="661" alt="Screenshot 2022-05-25 at 1 24 54 PM" src="https://user-images.githubusercontent.com/36672530/170210925-48d785e1-75c8-47e1-97f4-8eae7e97bf35.png">

2. Manual build by cloning this repo: 
after running : `./bootstrap.sh `
I get the following error: 
  mkdir build
  cd build
  bootstrap CC -g ../src/lua/lapi.c
  bootstrap CC -g ../src/lua/lauxlib.c
  bootstrap CC -g ../src/lua/lbaselib.c
  bootstrap CC -g ../src/lua/lcode.c
  bootstrap CC -g ../src/lua/lcorolib.c
  bootstrap CC -g ../src/lua/lctype.c
  bootstrap CC -g ../src/lua/ldblib.c
  bootstrap CC -g ../src/lua/ldebug.c
  bootstrap CC -g ../src/lua/ldo.c
  bootstrap CC -g ../src/lua/ldump.c
  bootstrap CC -g ../src/lua/lfunc.c
  bootstrap CC -g ../src/lua/lgc.c
  bootstrap CC -g ../src/lua/linit.c
  bootstrap CC -g ../src/lua/liolib.c
  bootstrap CC -g ../src/lua/llex.c
  bootstrap CC -g ../src/lua/lmathlib.c
  bootstrap CC -g ../src/lua/lmem.c
  bootstrap CC -g ../src/lua/loadlib.c
  bootstrap CC -g ../src/lua/lobject.c
  bootstrap CC -g ../src/lua/lopcodes.c
  bootstrap CC -g ../src/lua/loslib.c
  bootstrap CC -g ../src/lua/lparser.c
  bootstrap CC -g ../src/lua/lstate.c
  bootstrap CC -g ../src/lua/lstring.c
  bootstrap CC -g ../src/lua/lstrlib.c
  bootstrap CC -g ../src/lua/ltable.c
  bootstrap CC -g ../src/lua/ltablib.c
  bootstrap CC -g ../src/lua/ltm.c
  bootstrap CC -g ../src/lua/lua.c
  bootstrap CC -g ../src/lua/luac.c
  bootstrap CC -g ../src/lua/lundump.c
  bootstrap CC -g ../src/lua/lutf8lib.c
  bootstrap CC -g ../src/lua/lvm.c
  bootstrap CC -g ../src/lua/lzio.c
  link lua
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/bin.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/ccache.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/colors.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/config.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/create_name_file.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/db.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/debug.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/delete_name_file.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/dircache.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/entry.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/environ.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/estring.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/file.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/fslurp.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/graph.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/if_stmt.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/init.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/lock.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/logging.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/luaparser.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/mempool.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/option.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/parser.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/path.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/pel_group.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/platform.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/progress.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/send_event.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/string_tree.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/tent_list.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/tent_tree.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/thread_tree.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/timespan.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/tupid_list.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/tupid_tree.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/updater.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/vardb.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/vardict.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/variant.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/varsed.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/tup/main.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/monitor/null.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/flock/fcntl.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/inih/ini.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_byte_order.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_chartables.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_compile.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_config.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_dfa_exec.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_exec.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_fullinfo.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_get.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_globals.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_maketables.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_newline.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_ord2utf8.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_refcount.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_string_utils.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_study.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_tables.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_ucd.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_valid_utf8.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_version.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/pcre/pcre_xclass.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/server/fuse_fs.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/server/fuse_server.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/server/master_fork.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/tup/server/symlink.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/compat/dummy.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/compat/clearenv.c
  bootstrap CC -g -DTUP_SERVER="fuse" -DHAVE_CONFIG_H ../src/sqlite3/sqlite3.c
  bootstrap LD tup  -lm
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.027s] Reading in new environment variables...
[ tup ] [0.027s] Parsing Tupfiles...
mount_macfuse: the file system is not available (1)
tup error: Timed out waiting for the FUSE file-system to be ready.
tup error: Unable to mount FUSE on .tup/mnt

My system information: 
<img width="262" alt="Screenshot 2022-05-25 at 1 31 01 PM" src="https://user-images.githubusercontent.com/36672530/170212157-682c12c6-816c-44cc-b3ca-359f3ad7ff77.png">

**Comment by gittup** [comment]
Off-hand I'm not sure, but hopefully we can get the local compile working since it works on my mac.

Are you able to run other FUSE applications, like sshfs? Do you see fuse in the output from `kextstat` in the terminal?

**Comment by satishgaurav** [comment]
macFuse wasn't installed properly. I had to boot mac into 'reduced security mode' and give permission from **System Preferences** 

```
`kextstat -l | grep -v apple`

Executing: /usr/bin/kmutil showloaded --list-only
No variant specified, falling back to release
  238    0 0xfffffe0006f24000 0x4000     0x4000     io.macfuse.filesystems.macfuse (2097.20) 14248D75-9C85-359E-875E-A704E43AFDEE <7 5 4 3 1>
```
After that, I build it manually. It worked perfectly. Thank you !!!
