### ISSUE TITLE
Unable to clean deps file on Windows 11

### ISSUE THREAD

**Issue by jacereda** [gittup/tup#471]
Basically the same as: https://github.com/gittup/tup/issues/83

It's quite easy to reproduce, just make an invocation to `cl` on something that fails to compile and try rebuilding again quickly.

This is what I get:

```
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.407s] Reading in new environment variables...
[ tup ] [0.407s] No Tupfiles to parse.
[ tup ] [0.407s] No files to delete.
[ tup ] [0.407s] Executing Commands...
deps-36688: Permission denied
tup error: Unable to clean out a file in .tup/tmp directory. Please try cleaning this directory manually. Note there may be a stuck sub-process that still has the file open (check the Task Manager).
```

Triggering the build again after something like 15 seconds succeeds.

**Comment by gittup** [comment]
Thanks for the report! I was able to reproduce it - from ProcMon it looks like this is VCTIP.EXE that hangs around a bit after the build finishes. I've patched tup to ignore that executable (similar to mspdbsrv). Strangely for me, I have Visual Studio telemetry turned off, but VCTIP still runs.

Can you try https://gittup.org/tup/win32/tup-v0.7.11-95-g4e9f5b32.zip and see if that fixes it for you? If that doesn't work, I may try a more general solution of not complaining when a deps file can't be removed (along with adding the tup PID in the filename so repeated invocations use differently named files). Though it is somewhat useful to see when these other processes stick around afterwards so I know to ignore them.

**Comment by jacereda** [comment]
That version looks good, thanks!
