### ISSUE TITLE
File order in foreach rule

### ISSUE THREAD

**Issue by pinicarus** [gittup/tup#508]
Hello,

I have a foreach rule for a set of files with names made of hexadecimal digits, each producing its own output file and all of them collected in a `{bin}`.

I then have a rule using this bin as input, whose command needs to have the files lexicographically sorted by name.

It looks like they are already sorted when added to the bin.
The manual does not specify if this is guaranteed behavior.
Is it?

Best regards.

**Comment by gittup** [comment]
The relevant SQL query (https://github.com/gittup/tup/blob/4247a523587df54bd4a65ec42c4247a8488c050e/src/tup/db.c#L1396) doesn't have an ORDER BY clause in it, and tup doesn't do any sorting of the results, so it might just depend on the internal details of sqlite unless I'm missing something.

Although it appears to be sorted as you describe, I would suggest passing the filenames through sort before outputting them in case something changes in the future. Or if the command you are passing them to is something inside your project, you could sort the input names in the command itself.

**Comment by pinicarus** [comment]
OK, it's quite clear.

I will run the file list through `sort`.

Thanks.
